version: '3'

services:
    nginx:
        build:
            context: '.docker/nginx'
        ports:
          - 80:80
        volumes: 
          - ./index.html:/var/www/index.html
          - ./public:/var/www/public